export const LOGIN = 'LOGIN';
export const LOGIN_LOADING = 'LOGIN_LOADING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_LOADING = 'LOGOUT_LOADING';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_ERROR = 'LOGOUT_ERROR';

export const SIGNUP = 'SIGNUP';
export const SIGNUP_LOADING = 'SIGNUP_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const ADD_FILTER_ITEMS = 'ADD_FILTER_ITEMS';

export const GET_TASK_LIST = 'GET_TASK_LIST';
export const GET_TASK_LIST_LOADING = 'GET_TASK_LIST_LOADING';
export const GET_TASK_LIST_SUCCESS = 'GET_TASK_LIST_SUCCESS';
export const GET_TASK_LIST_ERROR = 'GET_TASK_LIST_ERROR';

export const GET_CURRENT_TASK_DETAILS = 'GET_CURRENT_TASK_DETAILS';
export const GET_CURRENT_TASK_DETAILS_LOADING = 'GET_CURRENT_TASK_DETAILS_LOADING';
export const GET_CURRENT_TASK_DETAILS_SUCCESS = 'GET_CURRENT_TASK_DETAILS_SUCCESS';
export const GET_CURRENT_TASK_DETAILS_ERROR = 'GET_CURRENT_TASK_DETAILS_ERROR';

export const CREATE_TASK = 'CREATE_TASK';
export const CREATE_TASK_LOADING = 'CREATE_TASK_LOADING';
export const CREATE_TASK_SUCCESS = 'CREATE_TASK_SUCCESS';
export const CREATE_TASK_ERROR = 'CREATE_TASK_ERROR';

export const GET_TASK_LABELS = 'GET_TASK_LABELS';
export const GET_TASK_LABELS_LOADING = 'GET_TASK_LABELS_LOADING';
export const GET_TASK_LABELS_SUCCESS = 'GET_TASK_LABELS_SUCCESS';
export const GET_TASK_LABELS_ERROR = 'GET_TASK_LABELS_ERROR';

export const GET_USERS = 'GET_USERS';
export const GET_USERS_LOADING = 'GET_USERS_LOADING';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_ERROR = 'GET_USERS_ERROR';
